import type { MetabaseThemeV2 } from "../../types";
import { DARK_THEME_ACCENT_COLORS } from "../accent-colors";
import { ds } from "../arena-ds";
import { getBaseColorsForThemeDefinitionOnly } from "../base-colors";

const baseColors = getBaseColorsForThemeDefinitionOnly();
const t = ds.dark;

// To be removed once the rename in GDGT-2517 is complete. Prefer the keys in
// `actualColors` below.
const deprecatedColors = {
  "admin-navbar": baseColors.octopus[80],
  "admin-navbar-secondary": baseColors.octopus[60],
  "admin-navbar-inverse": baseColors.octopus[60],
  "background-brand": baseColors.brand[90],
  "background-filter": baseColors.filter[90],
  "background-disabled": t.surface6,
  "background-disabled-inverse": t.textMutedInverse,
  "background-error-secondary": baseColors.lobster[90],
  "background-highlight":
    "color-mix(in srgb, var(--mb-color-core-brand) 7%, transparent)",
  "background-hover":
    "color-mix(in srgb, var(--mb-color-core-brand) 7%, transparent)",
  "background-selected":
    "color-mix(in srgb, var(--mb-color-core-brand) 21%, transparent)",
  "background-primary": t.bg,
  "background-secondary": t.surface1,
  "background-tertiary": t.surface5,
  "background-primary-inverse": ds.light.textPrimary,
  "background-secondary-inverse": t.textMuted,
  "background-tertiary-inverse": t.surface6,
  overlay: t.overlay,
  "background-error": baseColors.lobster[90],
  "background-success": baseColors.palm[90],
  "background-success-secondary": baseColors.palm[70],
  brand: baseColors.blue[40],
  "brand-hover": baseColors.brand[30],
  danger: baseColors.lobster[50],
  error: baseColors.lobster[50],
  filter: baseColors.octopus[40],
  focus: baseColors.blue[70],
  "icon-brand": baseColors.brand[40],
  "icon-primary": t.textIcon,
  "icon-disabled": t.textIconMuted,
  "icon-secondary": t.textSecondary,
  "illustration-brand-secondary": baseColors.brand[80],
  "illustration-brand-tertiary": baseColors.brand[90],
  "metabase-brand": baseColors.blue[40],
  "metabase-brand-hover": baseColors.blue[50],
  "saturated-blue": baseColors.ocean[40],
  "saturated-green": baseColors.palm[40],
  "saturated-purple": baseColors.octopus[40],
  "saturated-red": baseColors.lobster[40],
  "saturated-yellow": baseColors.dubloon[30],
  shadow: t.shadow,
  "success-secondary": baseColors.palm[40],
  success: baseColors.palm[50],
  summarize: baseColors.palm[40],
  "syntax-parameters-active": baseColors.mango[90],
  "syntax-parameters": baseColors.mango[40],
  "text-tertiary": t.textTertiary,
  "text-tertiary-inverse": t.textMuted,
  "text-hover": baseColors.brand[30],
  "text-secondary-opaque": t.textSecondary,
  warning: baseColors.dubloon[30],
  "background-warning": baseColors.dubloon[90],
  "background-warning-secondary": baseColors.dubloon[70],
  info: baseColors.orion[50],
  "background-info": baseColors.orion[90],
  white: t.bg,
  border: t.border,
  "border-strong": t.textMuted,
  "border-stronger": t.textTertiary,
  "border-subtle": t.surface5,
  gold: baseColors.gold,
  "upsell-primary": baseColors.ocean[30],
  "upsell-secondary": baseColors.ocean[80],
  "upsell-gem": baseColors.upsellGem,
};

const actualColors = {
  "background_page-filter": baseColors.filter[90],
  "background_page-highlighted":
    "color-mix(in srgb, var(--mb-color-core-brand) 7%, transparent)",
  "background_page-primary": t.bg,
  "background_page-primary-inverse": ds.white,
  "background_page-secondary": t.surface1,
  "background_page-secondary-inverse": ds.light.surface3,
  "background_page-tertiary": t.bg,
  "background_page-tertiary-inverse": t.textMutedInverse,
  "background_surface-brand-strong": baseColors.brand[20],
  "background_surface-brand-strong-hover": baseColors.brand[10],
  "background_surface-brand-strong-pressed": baseColors.brand[20],
  "background_surface-brand-subtle":
    "color-mix(in srgb, var(--mb-color-core-brand) 10%, transparent)",
  "background_surface-brand-subtle-hover":
    "color-mix(in srgb, var(--mb-color-core-brand), black 50%)",
  "background_surface-brand-subtle-pressed":
    "color-mix(in srgb, var(--mb-color-core-brand), black 75%)",
  "background_surface-disabled": t.surface6,
  "background_surface-disabled-inverse": t.textMutedInverse,
  "background_surface-error": baseColors.lobster[90],
  "background_surface-error-subtle": baseColors.lobster[90],
  "background_surface-hover":
    "color-mix(in srgb, var(--mb-color-core-brand) 7%, transparent)",
  "background_surface-primary": t.surface2,
  "background_surface-primary-hover": t.surfaceHover,
  "background_surface-primary-inverse": ds.white,
  "background_surface-primary-inverse-hover": ds.light.surface3,
  "background_surface-primary-inverse-pressed": t.textMutedInverse,
  "background_surface-primary-pressed": t.surfaceActive,
  "background_surface-secondary": t.surface1,
  "background_surface-secondary-hover": t.surfaceHover,
  "background_surface-secondary-inverse": ds.light.surface3,
  "background_surface-secondary-inverse-hover": t.textMutedInverse,
  "background_surface-secondary-inverse-pressed": t.textMuted,
  "background_surface-secondary-pressed": t.surfaceActive,
  "background_surface-selected":
    "color-mix(in srgb, var(--mb-color-core-brand) 21%, transparent)",
  "background_surface-success": baseColors.palm[90],
  "background_surface-warning": baseColors.dubloon[90],
  "background_surface-warning-strong": baseColors.dubloon[70],
  "border-brand": baseColors.brand[80],
  "border-filter": baseColors.filter[80],
  "border-highlight": baseColors.brand[30],
  "border-neutral": t.border,
  "border-neutral-strong": t.textMuted,
  "border-neutral-strongest": t.textTertiary,
  "border-neutral-subtle": t.surface5,
  "border-on_dark": t.border,
  "button-label-on_dark-disabled": t.textIconMuted,
  "button-label-on_dark-primary": ds.light.textPrimary,
  "button-label-on_dark-secondary": ds.white,
  "button-on_dark-disabled": t.surface6,
  "button-on_dark-primary-default": ds.white,
  "button-on_dark-primary-hover": t.textMutedInverse,
  "button-on_dark-primary-pressed": t.textMuted,
  "button-on_dark-secondary-default": t.surface6,
  "button-on_dark-secondary-hover": t.surfaceInvertedHover,
  "button-on_dark-secondary-pressed": t.surface6,
  "core-blue-saturated": baseColors.ocean[40],
  "core-brand-hover": baseColors.brand[30],
  "core-gold": baseColors.gold,
  "core-green-saturated": baseColors.palm[40],
  "core-info": baseColors.orion[50],
  "core-metabase_brand": baseColors.blue[40],
  "core-metabase_brand-hover": baseColors.blue[50],
  "core-purple-saturated": baseColors.octopus[40],
  "core-red-saturated": baseColors.lobster[40],
  "core-white": t.bg,
  "core-white_constant": ds.white,
  "core-yellow-saturated": baseColors.dubloon[30],
  "feedback-negative": baseColors.lobster[50],
  "feedback-negative-strong": baseColors.lobster[30],
  "feedback-neutral-strong": t.textMuted,
  "feedback-positive": baseColors.palm[50],
  "feedback-positive-selected": baseColors.palm[40],
  "feedback-positive-strong": baseColors.palm[20],
  "feedback-warning": baseColors.dubloon[30],
  "feedback-warning-strong": baseColors.dubloon[20],
  "illustration-secondary-brand": baseColors.brand[80],
  "illustration-tertiary-brand": baseColors.brand[90],
  "input-focus": baseColors.blue[70],
  "modal-overlay": t.overlay,
  "navbar-admin": baseColors.octopus[80],
  "navbar-admin-inverse": baseColors.octopus[60],
  "navbar-admin-secondary": baseColors.octopus[60],
  "shadow-default": t.shadow,
  "switch-off": t.surface6,
  "text-brand": baseColors.brand[40],
  "text-brand-hover": baseColors.brand[30],
  "text-brand-strong": baseColors.brand[20],
  "text-brand-strong-hover": baseColors.brand[10],
  "text-disabled": t.textMuted,
  "text-disabled-inverse": t.textMuted,
  "text-filter": baseColors.filter[30],
  "text-primary": t.textPrimary,
  "text-primary-inverse": t.textInverse,
  "text-secondary": t.textSecondary,
  "text-secondary-inverse": t.surface6,
  "text-selected": ds.white,
  "text-syntax-parameter": baseColors.mango[40],
  "text-syntax-parameter-active": baseColors.mango[90],
  "tooltip-background": t.surface5,
  "tooltip-background-focused": t.surface6,
  "tooltip-text": t.textPrimary,
  "tooltip-text-secondary": t.textSecondary,
};

/**
 * The default dark theme for Metabase.
 */
export const METABASE_DARK_THEME: MetabaseThemeV2 = {
  version: 2,
  chartColors: DARK_THEME_ACCENT_COLORS,
  colors: {
    ...deprecatedColors,
    ...actualColors,
  },
};
