import type { MetabaseThemeV2 } from "../../types";
import { LIGHT_THEME_ACCENT_COLORS } from "../accent-colors";
import { ds } from "../arena-ds";
import { getBaseColorsForThemeDefinitionOnly } from "../base-colors";

const baseColors = getBaseColorsForThemeDefinitionOnly();

// To be removed once the rename in GDGT-2517 is complete. Prefer the keys in
// `actualColors` below.
const deprecatedColors = {
  "admin-navbar": baseColors.octopus[60],
  "admin-navbar-secondary": baseColors.octopus[40],
  "admin-navbar-inverse": baseColors.octopus[80],
  "background-brand": baseColors.brand[10],
  "background-filter": baseColors.filter[5],
  "background-disabled": ds.grey[200],
  "background-disabled-inverse": ds.grey[800],
  "background-error-secondary": ds.error[50],
  "background-highlight":
    "color-mix(in srgb, var(--mb-color-core-brand) 7%, transparent)",
  "background-hover":
    "color-mix(in srgb, var(--mb-color-core-brand) 7%, transparent)",
  "background-selected":
    "color-mix(in srgb, var(--mb-color-core-brand) 21%, transparent)",
  "background-primary": ds.white,
  "background-secondary": ds.grey[50],
  "background-tertiary": ds.grey[200],
  "background-primary-inverse": ds.grey[900],
  "background-secondary-inverse": ds.grey[800],
  "background-tertiary-inverse": ds.grey[600],
  overlay: ds.overlay.light,
  "background-error": ds.error[50],
  "background-success": ds.success[50],
  "background-success-secondary": ds.success[300],
  brand: ds.blue[600],
  "brand-hover": baseColors.brand[50],
  danger: ds.error[600],
  error: ds.error[600],
  filter: baseColors.octopus[50],
  focus: ds.focusRing.light,
  "icon-brand": ds.blue[600],
  "icon-primary": ds.grey[900],
  "icon-disabled": ds.grey[300],
  "icon-secondary": ds.grey[700],
  "illustration-brand-secondary": baseColors.brand[10],
  "illustration-brand-tertiary": baseColors.brand[5],
  "metabase-brand": baseColors.blue[40],
  "metabase-brand-hover": baseColors.blue[30],
  "saturated-blue": ds.blue[600],
  "saturated-green": ds.success[600],
  "saturated-purple": ds.purple[600],
  "saturated-red": ds.error[600],
  "saturated-yellow": ds.yellow[600],
  shadow: ds.shadow.light,
  "success-secondary": ds.success[700],
  success: ds.success[600],
  summarize: ds.success[600],
  "syntax-parameters-active": baseColors.mango[10],
  "syntax-parameters": baseColors.mango[60],
  "text-tertiary": ds.grey[500],
  "text-tertiary-inverse": ds.grey[400],
  "text-hover": ds.blue[700],
  "text-secondary-opaque": ds.grey[700],
  warning: ds.warning[600],
  "background-warning": ds.warning[50],
  "background-warning-secondary": ds.warning[300],
  info: ds.blue[700],
  "background-info": ds.blue[50],
  white: ds.white,
  border: ds.grey[200],
  "border-strong": ds.grey[400],
  "border-stronger": ds.grey[600],
  "border-subtle": ds.grey[50],
  gold: baseColors.gold,
  "upsell-primary": baseColors.ocean[70],
  "upsell-secondary": baseColors.ocean[20],
  "upsell-gem": baseColors.upsellGem,
};

const actualColors = {
  "background_page-filter": baseColors.filter[5],
  "background_page-highlighted":
    "color-mix(in srgb, var(--mb-color-core-brand) 7%, transparent)",
  "background_page-primary": ds.white,
  "background_page-primary-inverse": ds.grey[900],
  "background_page-secondary": ds.grey[50],
  "background_page-secondary-inverse": ds.grey[950],
  "background_page-tertiary": ds.grey[200],
  "background_page-tertiary-inverse": ds.black,
  "background_surface-brand-strong": baseColors.brand[60],
  "background_surface-brand-strong-hover": baseColors.brand[70],
  "background_surface-brand-strong-pressed": baseColors.brand[80],
  "background_surface-brand-subtle":
    "color-mix(in srgb, var(--mb-color-core-brand) 10%, transparent)",
  "background_surface-brand-subtle-hover":
    "color-mix(in srgb, var(--mb-color-core-brand) 30%, transparent)",
  "background_surface-brand-subtle-pressed":
    "color-mix(in srgb, var(--mb-color-core-brand) 60%, transparent)",
  "background_surface-disabled": ds.grey[200],
  "background_surface-disabled-inverse": ds.grey[800],
  "background_surface-error": ds.error[50],
  "background_surface-error-subtle": ds.error[50],
  "background_surface-hover":
    "color-mix(in srgb, var(--mb-color-core-brand) 7%, transparent)",
  "background_surface-primary": ds.white,
  "background_surface-primary-hover": ds.grey[50],
  "background_surface-primary-inverse": ds.grey[900],
  "background_surface-primary-inverse-hover": ds.grey[800],
  "background_surface-primary-inverse-pressed": ds.grey[700],
  "background_surface-primary-pressed": ds.grey[200],
  "background_surface-secondary": ds.grey[50],
  "background_surface-secondary-hover": ds.grey[200],
  "background_surface-secondary-inverse": ds.grey[800],
  "background_surface-secondary-inverse-hover": ds.grey[700],
  "background_surface-secondary-inverse-pressed": ds.grey[800],
  "background_surface-secondary-pressed": ds.grey[300],
  "background_surface-selected":
    "color-mix(in srgb, var(--mb-color-core-brand) 21%, transparent)",
  "background_surface-success": ds.success[50],
  "background_surface-warning": ds.warning[50],
  "background_surface-warning-strong": ds.warning[300],
  "border-brand": baseColors.brand[10],
  "border-filter": baseColors.filter[20],
  "border-highlight": ds.blue[600],
  "border-neutral": ds.grey[200],
  "border-neutral-strong": ds.grey[400],
  "border-neutral-strongest": ds.grey[600],
  "border-neutral-subtle": ds.grey[50],
  "border-on_dark": ds.grey[800],
  "button-label-on_dark-disabled": ds.grey[600],
  "button-label-on_dark-primary": ds.grey[900],
  "button-label-on_dark-secondary": ds.white,
  "button-on_dark-disabled": ds.grey[800],
  "button-on_dark-primary-default": ds.white,
  "button-on_dark-primary-hover": ds.grey[200],
  "button-on_dark-primary-pressed": ds.grey[300],
  "button-on_dark-secondary-default": ds.grey[800],
  "button-on_dark-secondary-hover": ds.grey[700],
  "button-on_dark-secondary-pressed": ds.grey[800],
  "core-blue-saturated": ds.blue[600],
  "core-brand-hover": baseColors.brand[50],
  "core-gold": baseColors.gold,
  "core-green-saturated": ds.success[600],
  "core-info": ds.blue[700],
  "core-metabase_brand": baseColors.blue[40],
  "core-metabase_brand-hover": baseColors.blue[30],
  "core-purple-saturated": ds.purple[600],
  "core-red-saturated": ds.error[600],
  "core-white": ds.white,
  "core-white_constant": ds.white,
  "core-yellow-saturated": ds.yellow[600],
  "feedback-negative": ds.error[600],
  "feedback-negative-strong": ds.error[800],
  "feedback-neutral-strong": ds.grey[600],
  "feedback-positive": ds.success[600],
  "feedback-positive-selected": ds.success[700],
  "feedback-positive-strong": ds.success[800],
  "feedback-warning": ds.warning[600],
  "feedback-warning-strong": ds.warning[800],
  "illustration-secondary-brand": baseColors.brand[10],
  "illustration-tertiary-brand": baseColors.brand[5],
  "input-focus": ds.focusRing.light,
  "modal-overlay": ds.overlay.light,
  "navbar-admin": baseColors.octopus[60],
  "navbar-admin-inverse": baseColors.octopus[80],
  "navbar-admin-secondary": baseColors.octopus[40],
  "shadow-default": ds.shadow.light,
  "switch-off": ds.grey[200],
  "text-brand": ds.blue[600],
  "text-brand-hover": ds.blue[700],
  "text-brand-strong": ds.blue[700],
  "text-brand-strong-hover": ds.blue[800],
  "text-disabled": ds.grey[300],
  "text-disabled-inverse": ds.grey[600],
  "text-filter": baseColors.filter[50],
  "text-primary": ds.grey[900],
  "text-primary-inverse": ds.white,
  "text-secondary": ds.grey[700],
  "text-secondary-inverse": ds.grey[300],
  "text-selected": ds.grey[900],
  "text-syntax-parameter": baseColors.mango[60],
  "text-syntax-parameter-active": baseColors.mango[10],
  "tooltip-background": ds.grey[900],
  "tooltip-background-focused": ds.grey[950],
  "tooltip-text": ds.white,
  "tooltip-text-secondary": ds.grey[300],
};

/**
 * The default light theme for Metabase.
 */
export const METABASE_LIGHT_THEME: MetabaseThemeV2 = {
  version: 2,
  chartColors: LIGHT_THEME_ACCENT_COLORS,
  colors: {
    ...deprecatedColors,
    ...actualColors,
  },
};
