import type { MetabaseThemeV2 } from "../../types";
import { LIGHT_THEME_ACCENT_COLORS } from "../accent-colors";
import { ds } from "../arena-ds";
import { getBaseColorsForThemeDefinitionOnly } from "../base-colors";

const baseColors = getBaseColorsForThemeDefinitionOnly();
const t = ds.light;

// To be removed once the rename in GDGT-2517 is complete. Prefer the keys in
// `actualColors` below.
const deprecatedColors = {
  "admin-navbar": baseColors.octopus[60],
  "admin-navbar-secondary": baseColors.octopus[40],
  "admin-navbar-inverse": baseColors.octopus[80],
  "background-brand": baseColors.brand[10],
  "background-filter": baseColors.filter[5],
  "background-disabled": t.surface6,
  "background-disabled-inverse": t.surfaceInvertedHover,
  "background-error-secondary": baseColors.lobster[5],
  "background-highlight":
    "color-mix(in srgb, var(--mb-color-core-brand) 7%, transparent)",
  "background-hover":
    "color-mix(in srgb, var(--mb-color-core-brand) 7%, transparent)",
  "background-selected":
    "color-mix(in srgb, var(--mb-color-core-brand) 21%, transparent)",
  "background-primary": t.bg,
  "background-secondary": t.surface1,
  "background-tertiary": t.surface6,
  "background-primary-inverse": t.surfaceInverted,
  "background-secondary-inverse": t.surfaceInvertedHover,
  "background-tertiary-inverse": t.textMuted,
  overlay: t.overlay,
  "background-error": baseColors.lobster[10],
  "background-success": baseColors.palm[5],
  "background-success-secondary": baseColors.palm[20],
  brand: baseColors.blue[40],
  "brand-hover": baseColors.brand[50],
  danger: baseColors.lobster[50],
  error: baseColors.lobster[50],
  filter: baseColors.octopus[50],
  focus: baseColors.blue[20],
  "icon-brand": baseColors.brand[50], // Matches text-brand
  "icon-brand-inverse": baseColors.brand[20],
  "icon-primary": baseColors.orionAlpha[80], // Matches text-primary
  "icon-primary-inverse": baseColors.orionAlphaInverse[80], // Matches text-primary-inverse
  "icon-disabled": baseColors.orionAlpha[40], // Matches text-disabled
  "icon-disabled-inverse": baseColors.orionAlphaInverse[40], // Matches text-disabled-inverse
  "icon-secondary": baseColors.orionAlpha[60], // Matches text-secondary
  "icon-secondary-inverse": baseColors.orionAlphaInverse[60], // Matches text-secondary-inverse
  "illustration-brand-secondary": baseColors.brand[10],
  "illustration-brand-tertiary": baseColors.brand[5],
  "metabase-brand": baseColors.blue[40],
  "metabase-brand-hover": baseColors.blue[30],
  "saturated-blue": baseColors.ocean[60],
  "saturated-green": baseColors.palm[60],
  "saturated-purple": baseColors.octopus[60],
  "saturated-red": baseColors.lobster[60],
  "saturated-yellow": baseColors.dubloon[30],
  shadow: t.shadow,
  "success-secondary": baseColors.palm[60],
  success: baseColors.palm[50],
  summarize: baseColors.palm[50],
  "syntax-parameters-active": baseColors.mango[10],
  "syntax-parameters": baseColors.mango[60],
  "text-tertiary": t.textTertiary,
  "text-tertiary-inverse": t.textMutedInverse,
  "text-hover": baseColors.brand[60],
  "text-secondary-opaque": t.textSecondary,
  warning: baseColors.dubloon[30],
  "background-warning": baseColors.dubloon[5],
  "background-warning-secondary": baseColors.dubloon[20],
  info: baseColors.orion[40],
  "background-info": baseColors.orion[10],
  white: ds.white,
  border: t.border,
  "border-strong": t.textMutedInverse,
  "border-stronger": t.textMuted,
  "border-subtle": t.border1,
  gold: baseColors.gold,
  "upsell-primary": baseColors.ocean[70],
  "upsell-secondary": baseColors.ocean[20],
  "upsell-gem": baseColors.upsellGem,
};

const actualColors = {
  "background_page-filter": baseColors.filter[5],
  "background_page-highlighted":
    "color-mix(in srgb, var(--mb-color-core-brand) 7%, transparent)",
  "background_page-primary": t.bg,
  "background_page-primary-inverse": t.surfaceInverted,
  "background_page-secondary": t.surface1,
  "background_page-secondary-inverse": t.surfaceInverted,
  "background_page-tertiary": t.surface6,
  "background_page-tertiary-inverse": ds.black,
  "background_surface-brand-strong": baseColors.brand[60],
  "background_surface-brand-strong-hover": baseColors.brand[70],
  "background_surface-brand-strong-pressed": baseColors.brand[80],
  "background_surface-brand-subtle":
    "color-mix(in srgb, var(--mb-color-core-brand) 10%, transparent)",
  "background_surface-brand-subtle-hover":
    "color-mix(in srgb, var(--mb-color-core-brand) 30%, transparent)",
  "background_surface-brand-subtle-pressed":
    "color-mix(in srgb, var(--mb-color-core-brand) 60%, transparent)",
  "background_surface-disabled": t.surface6,
  "background_surface-disabled-inverse": t.surfaceInvertedHover,
  "background_surface-error": baseColors.lobster[10],
  "background_surface-error-subtle": baseColors.lobster[5],
  "background_surface-hover":
    "color-mix(in srgb, var(--mb-color-core-brand) 7%, transparent)",
  "background_surface-primary": t.surface2,
  "background_surface-primary-hover": t.surfaceHover,
  "background_surface-primary-inverse": t.surfaceInverted,
  "background_surface-primary-inverse-hover": t.surfaceInvertedHover,
  "background_surface-primary-inverse-pressed": t.borderInverted,
  "background_surface-primary-pressed": t.surfaceActive,
  "background_surface-secondary": t.surface3,
  "background_surface-secondary-hover": t.surfaceHover,
  "background_surface-secondary-inverse": t.surfaceInvertedHover,
  "background_surface-secondary-inverse-hover": t.borderInverted,
  "background_surface-secondary-inverse-pressed": t.surfaceInvertedHover,
  "background_surface-secondary-pressed": t.surfaceActive,
  "background_surface-selected":
    "color-mix(in srgb, var(--mb-color-core-brand) 21%, transparent)",
  "background_surface-success": baseColors.palm[5],
  "background_surface-warning": baseColors.dubloon[5],
  "background_surface-warning-strong": baseColors.dubloon[20],
  "border-brand": baseColors.brand[10],
  "border-filter": baseColors.filter[20],
  "border-highlight": baseColors.brand[30],
  "border-neutral": t.border,
  "border-neutral-strong": t.textMutedInverse,
  "border-neutral-strongest": t.textMuted,
  "border-neutral-subtle": t.border1,
  "border-on_dark": t.borderInverted,
  "button-label-on_dark-disabled": t.textMuted,
  "button-label-on_dark-primary": t.textPrimary,
  "button-label-on_dark-secondary": t.textInverse,
  "button-on_dark-disabled": t.surfaceInvertedHover,
  "button-on_dark-primary-default": ds.white,
  "button-on_dark-primary-hover": t.surface6,
  "button-on_dark-primary-pressed": t.surfaceActive,
  "button-on_dark-secondary-default": t.surfaceInvertedHover,
  "button-on_dark-secondary-hover": t.borderInverted,
  "button-on_dark-secondary-pressed": t.surfaceInvertedHover,
  "core-blue-saturated": baseColors.ocean[60],
  "core-brand-hover": baseColors.brand[50],
  "core-gold": baseColors.gold,
  "core-green-saturated": baseColors.palm[60],
  "core-info": baseColors.orion[40],
  "core-metabase_brand": baseColors.blue[40],
  "core-metabase_brand-hover": baseColors.blue[30],
  "core-purple-saturated": baseColors.octopus[60],
  "core-red-saturated": baseColors.lobster[60],
  "core-white": ds.white,
  "core-white_constant": ds.white,
  "core-yellow-saturated": baseColors.dubloon[30],
  "feedback-negative": baseColors.lobster[50],
  "feedback-negative-strong": baseColors.lobster[60],
  "feedback-neutral-strong": t.textMuted,
  "feedback-positive": baseColors.palm[50],
  "feedback-positive-selected": baseColors.palm[60],
  "feedback-positive-strong": baseColors.palm[60],
  "feedback-warning": baseColors.dubloon[30],
  "feedback-warning-strong": baseColors.mango[60],
  "illustration-secondary-brand": baseColors.brand[10],
  "illustration-tertiary-brand": baseColors.brand[5],
  "input-background": baseColors.orionAlpha[5],
  "input-focus": baseColors.blue[20],
  "modal-overlay": t.overlay,
  "navbar-admin": baseColors.octopus[60],
  "navbar-admin-inverse": baseColors.octopus[80],
  "navbar-admin-secondary": baseColors.octopus[40],
  "shadow-default": t.shadow,
  "switch-off": t.surface6,
  "switch-checked": baseColors.brand[60],
  "switch-disabled": baseColors.orionAlpha[20],
  "switch-unchecked": baseColors.orionAlpha[30],
  "switch_thumb-disabled": baseColors.white,
  "text-brand": baseColors.brand[50],
  "text-brand-hover": baseColors.brand[60],
  "text-brand-strong": baseColors.brand[60],
  "text-brand-strong-hover": baseColors.brand[70],
  "text-disabled": t.textMuted,
  "text-disabled-inverse": t.textMuted,
  "text-filter": baseColors.filter[50],
  "text-primary": t.textPrimary,
  "text-primary-inverse": t.textInverse,
  "text-secondary": t.textSecondary,
  "text-secondary-inverse": t.textMutedInverse,
  "text-selected": t.textPrimary,
  "text-syntax-parameter": baseColors.mango[60],
  "text-syntax-parameter-active": baseColors.mango[10],
  "tooltip-background": t.surfaceInverted,
  "tooltip-background-focused": t.surfaceInvertedHover,
  "tooltip-text": t.textInverse,
  "tooltip-text-secondary": t.textMutedInverse,
};

/**
 * The default light theme for Metabase.
 */
export const METABASE_LIGHT_THEME: MetabaseThemeV2 = {
  version: 2,
  chartColors: LIGHT_THEME_ACCENT_COLORS,
  colors: {
    ...deprecatedColors,
    ...actualColors,
  },
};
